# Определение версии Docker Compose и начало описания сервисо
version: '3'

services:
   web-app:
       # Сборка образа для сервиса django из текущей директории
       build:
         context: .
       ports:
           - '8000:8000'
       volumes:
        - ./engineer:/engineer